[package]
name = "pdblister"
version = "0.1.0"
authors = ["Gogs <gogs@fake.local>"]
edition = "2018"

[dependencies]
anyhow = "1.0.41"
futures = "0.3.13"
indicatif = { git = "https://github.com/mitsuhiko/indicatif.git", branch = "main" }
pin-utils = "0.1.0"
rand = "0.3"
reqwest = "0.11.0"
thiserror = "1.0.25"

[dependencies.tokio]
version = "1.7.1"
features = ["full"]
