[package]
name = "pdblister"
version = "0.1.0"
authors = ["Gogs <gogs@fake.local>"]
edition = "2018"

[dependencies]
futures = "0.3.13"
indicatif = "0.15.0"
pin-utils = "0.1.0"
rand = "0.3"
reqwest = "0.10.8"

[dependencies.tokio]
version = "1.7.1"
features = ["full"]
